apiVersion: v1
kind: Pod
metadata:
  labels:
    run: qos-demo-2
  name: qos-demo-2  
spec:
  containers:
  - name: qos-demo-2-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "100Mi"
        cpu: "500m"

