apiVersion: v1
data:
  nginx.conf: |
    events {} 

    http {
      server {
        listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/tls/certificado.crt;
        ssl_certificate_key /etc/nginx/tls/chave-privada.key;

        location / {
          return 200 'Olá terraqueos e extraterrestres!\n';
          add_header Content-type text/plain;
        }
      }
    }

kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
  resourceVersion: "4435384"
  uid: 58d9bbd0-71e9-4ad4-ae56-e8ed3e69e41a
