apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: vsphere        
  name: pv-vsphere
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  vsphereVolume:
    volumePath: "[DataFileStorage] k8s/k8s.vmdk"
    fsType: ext4
  storageClassName: witty  
