apiVersion: v1
kind: Service
metadata:
  name: locust-giropops
spec:
  type: NodePort      
  selector:
    app: locust-giropops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
      nodePort: 30080
