apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs      
  name: www
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs
    server: 172.10.0.15
    readOnly: false
  storageClassName: www  
