apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: nfs
  name: managed-nfs-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs
  storageClassName: managed-nfs-storage
