apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    storage: nfs      
  name: www
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 800Mi
  storageClassName: www
  volumeName: www
  selector:
    matchLabels:
      storage: nfs 

