apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: nginx-persistent-storage
  name: nginx-persistent-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  selector:
    matchLabels:
      storage: nginx-persistent-storage

