apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-pv
provisioner: kubernets.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"
