apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
  - image: nginx
    name: nginx-giropops
    ports:
    - containerPort: 80
    resources: 
      limits: 
        memory: "64Mi"
        cpu: "5m"
    requests:
      memory: "4400Mi"
      cpu: "3m"
  dnsPolicy: ClusterSecond
  restartPolicy: Always
