---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-giropops
spec:
  containers:
  - name: nginx-giropops
    image: nginx
    ports:
    - containerPort: 80        
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
